tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "raycast"

brew "exa"
brew "stow"
brew "neovim"
brew "node", link: false
brew "ripgrep"
brew "starship"
brew "tmux"
brew "tree"
brew "yarn"
brew "jesseduffield/lazydocker/lazydocker"
brew "jesseduffield/lazygit/lazygit"

cask "raycast"
cask "font-jetbrainsmono-nerd-font"
cask "iterm2"
cask "fig"
